/**
 * Type definitions for Docusaurus Physical AI Textbook Platform
 *
 * This file contains all TypeScript interfaces and types used across the application,
 * including entities, API contracts, and UI state management.
 */

// ============================================================================
// Core Entities
// ============================================================================

/**
 * Chapter: A self-contained educational unit covering a specific topic
 */
export interface Chapter {
  id: string;              // Unique identifier (e.g., "ch-ros2-nodes")
  path: string;            // URL path (e.g., "/docs/module-1/nodes")
  title: string;           // Display title (e.g., "ROS 2 Nodes and Topics")
  module: string;          // Parent module ID (e.g., "module-1-ros2")
  order: number;           // Sequence within module (e.g., 1, 2, 3)
  content: string;         // Markdown content (loaded by Docusaurus)
}

/**
 * Module: A thematic grouping of related chapters
 */
export interface Module {
  id: string;              // Unique identifier (e.g., "module-1-ros2")
  title: string;           // Display title (e.g., "Module 1: ROS 2 Fundamentals")
  description: string;     // Brief overview
  order: number;           // Sequence in curriculum (1, 2, 3, 4)
  chapters: Chapter[];     // Child chapters
}

// ============================================================================
// Chatbot API Types
// ============================================================================

/**
 * ChatbotQuery: A user-submitted question with optional selected text context
 */
export interface ChatbotQuery {
  query_text: string;         // User's question (max 1000 characters)
  chapter_id: string | null;  // Current chapter ID (e.g., "ch-ros2-nodes")
  user_id: string;            // User identifier (default: "guest-user")
  selected_text?: string;     // Optional highlighted text (max 500 characters)
}

/**
 * GroundingStatus: Indicates how well the answer is grounded in textbook content
 */
export type GroundingStatus = 'fully_grounded' | 'partially_grounded' | 'speculative';

/**
 * SourceCitation: A reference to a specific textbook section used to generate an answer
 */
export interface SourceCitation {
  chunk_id: string;          // Vector DB chunk identifier
  chapter_id: string;        // Chapter reference (e.g., "ch-ros2-nodes")
  section_title: string;     // Section heading (e.g., "Node Communication")
  content_excerpt: string;   // Text snippet (first 200 chars of chunk)
  similarity_score: number;  // 0.0-1.0 (cosine similarity to query)
  page_number?: number;      // Optional page reference (if applicable)
}

/**
 * ChatbotResponse: An answer generated by the RAG system with source citations and metadata
 */
export interface ChatbotResponse {
  answer: string;                    // Generated answer text
  sources: SourceCitation[];         // Relevant textbook sections
  confidence_score: number;          // 0.0-1.0 (avg similarity of top 3 sources)
  grounding_status: GroundingStatus; // fully_grounded | partially_grounded | speculative
  processing_time_ms: number;        // Backend processing time
  metadata: {
    query_text: string;              // Original query (for history)
    chapter_id: string | null;       // Context chapter
    timestamp: string;               // ISO 8601 datetime
  };
}

/**
 * StandardErrorResponse: Standardized error format from backend API
 */
export interface StandardErrorResponse {
  error_code: string;    // Error code (e.g., "CONTEXT_NOT_FOUND", "SERVICE_UNAVAILABLE")
  message: string;       // Human-readable error message
}

// ============================================================================
// UI State Types
// ============================================================================

/**
 * TextSelection: User-highlighted text on the current page
 */
export interface TextSelection {
  text: string;              // Selected text content
  range: DOMRect | null;     // Bounding box coordinates (for tooltip positioning)
  startOffset: number;       // Start character position
  endOffset: number;         // End character position
}

/**
 * ConversationTurn: A single question-answer exchange in the chatbot
 */
export interface ConversationTurn {
  query: ChatbotQuery;
  response: ChatbotResponse;
  timestamp: string;         // ISO 8601 datetime
}

/**
 * ChatbotWidgetState: State management for the chatbot widget component
 */
export interface ChatbotWidgetState {
  isOpen: boolean;                       // Widget expanded or collapsed
  currentQuery: string;                  // User's input text
  conversationHistory: ConversationTurn[]; // Past Q&A pairs
  isLoading: boolean;                    // Waiting for API response
  error: string | null;                  // Error message (if request failed)
}

/**
 * SelectionTooltipState: State management for the text selection tooltip
 */
export interface SelectionTooltipState {
  selection: TextSelection | null; // Current selection (null if none)
  isVisible: boolean;              // Tooltip shown or hidden
}

/**
 * ChapterContextState: State for tracking the current chapter context
 */
export interface ChapterContextState {
  currentChapterId: string | null; // Current page chapter ID
  currentPathname: string;         // URL pathname
}

// ============================================================================
// Configuration Types
// ============================================================================

/**
 * DocusaurusCustomFields: Custom fields defined in docusaurus.config.ts
 */
export interface DocusaurusCustomFields {
  apiUrl: string;       // Backend API URL
  apiTimeout: string;   // API request timeout in milliseconds
}

/**
 * ChapterMap: Mapping from URL pathname to chapter ID
 */
export type ChapterMap = Record<string, string | null>;

// ============================================================================
// Health Check Types
// ============================================================================

/**
 * HealthCheckResponse: Backend health check endpoint response
 */
export interface HealthCheckResponse {
  status: 'healthy' | 'unhealthy';
  timestamp: string;
  services: {
    vector_db: 'connected' | 'disconnected';
    llm: 'connected' | 'disconnected';
  };
}

// ============================================================================
// Validation Constants
// ============================================================================

/**
 * Validation constraints for query text
 */
export const QUERY_TEXT_MAX_LENGTH = 1000;
export const SELECTED_TEXT_MAX_LENGTH = 500;

/**
 * API timeout defaults (milliseconds)
 */
export const DEFAULT_API_TIMEOUT = 10000; // 10 seconds

/**
 * User ID for anonymous users
 */
export const GUEST_USER_ID = 'guest-user';
